# Generated by Django 5.2.7 on 2025-12-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0003_contact'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_user_contact',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'mobile_number')},
        ),
    ]
